const DATE_FORMAT = "YYYY-MM-DD (ddd)";
const SIMPLE_FORMAT = 'YYYYMMDD';
const DEFAULT_TASK_COLOR = 'rgba(175, 175, 175, 0.1)';

export {
    DATE_FORMAT,
    SIMPLE_FORMAT,
    DEFAULT_TASK_COLOR,
}
